name: kicad-tools

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  kicad:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/cache@v1
        id: kicad-tools
        with:
          path: /opt/kicad-tools
          key: ${{ runner.os }}-kicad

#      - uses: actions/cache@v1
#        id: docker
#        with:
#          path: ????
#          key: ${{ runner.os }}-docker

      - name: install kicad-tools
        if: steps.kicad-tools.outputs.cache-hit != 'true'
        run: git clone --branch=ci https://github.com/nnarain/kicad-tools /opt/kicad-tools
        
      - name: generate KiCAD output
#        if: steps.docker.outputs.cache-hit != 'true'
        id: run-kicad-tools
        env:
          DOCKER_CONTAINER: nnarain/kicad-tools
          DOCKER_INTERACTIVE: ""
          KICAD_TOOLS_PATH: /opt/kicad-tools
        run: cp /opt/kicad-tools/etc/Makefile ./Makefile && make fabrication-outputs

      - name: move output files
#        if: file generation successfull
        run: |
          PROJECT=$(basename "$PWD") 
          mkdir -p docs/bom && cp -u $(find out/ -name "bom.csv") "docs/bom/"$PROJECT"_bom.csv"
          mkdir -p docs/bom && cp -u $(find out/ -name "ibom.html") "docs/bom/index.html"
          mkdir -p docs && cp -u $(find out/ -name $PROJECT".pdf") "docs/"$PROJECT"_schematic.pdf"
          mkdir -p docs && cp -u $(find out/ -name $PROJECT".svg") "docs/"$PROJECT"_schematic.svg"
          mkdir -p gerber && cp -u $(find out/ -type f \( -iname \*.gbr -o -iname \*.drl \)) gerber/

      - name: run tracespace
#        if: file generation successfull
        run: |
          PROJECT=$(basename "$PWD") 
          sudo npm install -g @tracespace/cli
          tracespace -L --out=out gerber/*Cu.gbr gerber/*Mask.gbr gerber/*Paste.gbr gerber/*.drl gerber/*SilkS.gbr
          mkdir -p docs/img && mv -u $(find out/ -name $PROJECT"*top.svg") "docs/img/"$PROJECT"_layout_top.svg"
          mkdir -p docs/img && mv -u $(find out/ -name $PROJECT"*bottom.svg") "docs/img/"$PROJECT"_layout_bottom.svg"
          tracespace -L --out=out gerber/*Edge_Cuts.gbr gerber/*.drl gerber/*Fab.gbr
          mkdir -p docs/img && mv -u $(find out/ -name $PROJECT"*top.svg") "docs/img/"$PROJECT"_assembly_top.svg"
          mkdir -p docs/img && mv -u $(find out/ -name $PROJECT"*bottom.svg") "docs/img/"$PROJECT"_assembly_bottom.svg"

      - name: commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git stage docs/* && git stage gerber/*
          git commit -m "Add changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
