name: kicad-tools

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install git
      run:  |
            sudo apt install git
            git config --global user.email ""
            git config --global user.name "bot"

    - uses: actions/cache@v1
      id:   cache
      with:
        path: /var/cache
        key: ${{ runner.os }}-kicad

    - uses: actions/setup-python@v1
      with:
        python-version: '2.7'
    - run:  pip install svgwrite 

    - name: clone nerdyscout/kicad-tools
      if:   steps.cache.outputs.cache-hit != 'true'
      run:  |
            git clone https://github.com/nerdyscout/kicad-tools.git /opt/kicad-tools
            cd /opt/kicad-tools
            git checkout origin/ProMicro
            git submodule update --init
            make

    - name: make board
      run:  |
            cp /opt/kicad-tools/etc/Makefile ./Makefile
            make debug
            make gerbers
            make schematic
            make bom
            make interactive-bom
            rm -r -f gerber
            mkdir gerber
            rm -r -f docs
            mkdir docs
            mkdir docs/bom
            sudo mv out/ProMicro_SX1276-heads/master/schematic/svg/ProMicro_SX1276.svg docs/ProMicro_SX1276_schematic.svg
            sudo mv out/ProMicro_SX1276-heads/master/schematic/pdf/* docs/ProMicro_SX1276_schematic.pdf
            sudo mv out/ProMicro_SX1276-heads/master/bom/interactive/ibom.html docs/bom/index.html
            sudo mv out/ProMicro_SX1276-heads/master/bom/bom.csv docs/bom/ProMicro_SX1276_bom.csv
            sudo mv out/ProMicro_SX1276-heads/master/layout/gerber/* gerber/
            sudo rm -f ProMicro*.xml
            sudo rm -r -f out
            rm Makefile
            
    - name: commit results
      run:  |
            git stage .
            git commit -m "auto generated by github actions"

    - name: push results
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
